name: 🚀 Deploy Extension

on:
  workflow_call:
    secrets:
      marketplace-token:
        required: true

jobs:
  build:
    name: 🔨 Build Extension
    uses: ./.github/workflows/build.extension.yml

  deploy-extension:
    name: 🚀 Deploy Extension
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download Extension Package
        uses: actions/download-artifact@v4
        with:
          name: extension-package

      - name: 📦 Install VSCE
        run: |
          npm install -g @vscode/vsce

      - name: 🚀 Publish Extension
        run: |
          VSIX_FILE=$(ls *.vsix)
          vsce publish --packagePath "${VSIX_FILE}" --pat ${{ secrets.marketplace-token }}