name: 🚀 Deploy Services

on:
  workflow_call:
    secrets:
      azure-sql-connection-string:
        required: true

jobs:
  deploy-database:
    name: 🚀 Deploy Database
    uses: ./.github/workflows/deploy.database.yml
    secrets:
      azure-sql-connection-string: ${{ secrets.azure-sql-connection-string }}